// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk1egy82nuzFfV4F6m7Yp9RWwRHyqSGeQ',
    appId: '1:488230873073:web:9c988c4745a9ab75670650',
    messagingSenderId: '488230873073',
    projectId: 'umkrides',
    authDomain: 'umkrides.firebaseapp.com',
    databaseURL: 'https://umkrides-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umkrides.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjI6yia4L5Szu-7cEHiWUZmGWLsWTC_nY',
    appId: '1:488230873073:android:fd2e40049f1f95a1670650',
    messagingSenderId: '488230873073',
    projectId: 'umkrides',
    databaseURL: 'https://umkrides-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umkrides.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-oyIafAswRcPGpffxj38WsOBHDL-KCi0',
    appId: '1:488230873073:ios:f68fce74f7097b60670650',
    messagingSenderId: '488230873073',
    projectId: 'umkrides',
    databaseURL: 'https://umkrides-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umkrides.firebasestorage.app',
    iosBundleId: 'com.example.umkrideFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-oyIafAswRcPGpffxj38WsOBHDL-KCi0',
    appId: '1:488230873073:ios:f68fce74f7097b60670650',
    messagingSenderId: '488230873073',
    projectId: 'umkrides',
    databaseURL: 'https://umkrides-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umkrides.firebasestorage.app',
    iosBundleId: 'com.example.umkrideFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk1egy82nuzFfV4F6m7Yp9RWwRHyqSGeQ',
    appId: '1:488230873073:web:3d226f7262c25b94670650',
    messagingSenderId: '488230873073',
    projectId: 'umkrides',
    authDomain: 'umkrides.firebaseapp.com',
    databaseURL: 'https://umkrides-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umkrides.firebasestorage.app',
  );
}
